import noScrollbar from './css-plugins/no-scrollbar.js';
import noSpinner from './css-plugins/no-spinner.js';
import scrollbar from './css-plugins/scrollbar.js';
import typography from './css-plugins/typography.js';
import perspective from './css-plugins/perspective.js';

const primitives = {
  colors: {
    amber: {
      50: '#FFFBEB',
      100: '#FEF3C7',
      200: '#FDE68A',
      300: '#FCD34D',
      400: '#FBBF24',
      500: '#F59E0B',
      600: '#D97706',
      700: '#B45309',
      800: '#92400E',
      900: '#78350F',
      1100: '#391503',
    },
    green: {
      50: '#F0FDF4',
      100: '#DCFCE7',
      200: '#BBF7D0',
      300: '#86EFAC',
      400: '#4ADE80',
      500: '#22C55E',
      600: '#16A34A',
      700: '#15803D',
      800: '#166534',
      900: '#14532D',
      1100: '#0C3B1F',
    },
    fuchsia: {
      50: '#FDF4FF',
      100: '#FAE8FF',
      200: '#F5D0FE',
      300: '#F0ABFC',
      400: '#E879F9',
      500: '#D946EF',
      600: '#C026D3',
      700: '#A21CAF',
      800: '#86198F',
      900: '#701A75',
    },
    purple: {
      50: '##FFFBFF',
      100: '#F3EEFF',
      200: '#E3DFFF',
      300: '#C4C0FF',
      400: '#A6A1FD',
      500: '#8B87E0',
      600: '#726DC4',
      700: '#413B90',
      800: '#292278',
      900: '#171347',
    },
    red: {
      50: '#FEF2F2',
      100: '#FEE2E2',
      200: '#FECACA',
      300: '#FCA5A5',
      400: '#F87171',
      500: '#EF4444',
      600: '#DC2626',
      700: '#B91C1C',
      800: '#991B1B',
      900: '#7F1D1D',
      1100: '#391503',
    },
    blue: {
      50: '#EFF6FF',
      100: '#DBEAFE',
      200: '#BFDBFE',
      300: '#93C5FD',
      400: '#60A5FA',
      500: '#3B82F6',
      600: '#2563EB',
      700: '#1D4ED8',
      800: '#1E40AF',
      900: '#1E3A8A',
      1100: '#091842',
    },
    teal: {
      50: '#F0FDFA',
      100: '#CCFBF1',
      200: '#99F6E4',
      300: '#5EEAD4',
      400: '#2DD4BF',
      500: '#14B8A6',
      600: '#0D9488',
      700: '#0F766E',
      800: '#115E59',
      900: '#134E4A',
    },
    zinc: {
      50: '#FAFAFA',
      100: '#EEEEF0',
      200: '#E4E4E7',
      300: '#D4D4D8',
      400: '#A1A1AA',
      500: '#71717A',
      600: '#52525B',
      700: '#3F3F46',
      800: '#27272A',
      900: '#18181B',
      1000: '#0F0F11',
    },
    grey: {
      50: '#FFFFFF',
      100: '#F3F4F6',
      200: '#E4E4E7',
      300: '#D1D5DB',
      400: '#9CA3AF',
      500: '#6B7280',
      600: '#4B5563',
      700: '#374151',
      800: '#1F2937',
      900: '#111827',
      1100: '#020408',
    },
  },
  spacing: {
    '025': '1px',
    '05': '2px',
    1: '4px',
    2: '8px',
    3: '12px',
    4: '16px',
    5: '20px',
    6: '24px',
    8: '32px',
    10: '40px',
    12: '48px',
    16: '64px',
    20: '80px',
    24: '96px',
    32: '128px',
    40: '160px',
    48: '192px',
    60: '240px',
    64: '256px',
    'form-text-field-height': '36px',
  },
  fontSize: {
    xxs: '10px',
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '20px',
    xl: '24px',
    '2xl': '28px',
    '3xl': '32px',
    '4xl': '40px',
    '5xl': '56px',
    '6xl': '64px',
    '7xl': '72px',
  },
  lineHeight: {
    xxs: '14px',
    xs: '16px',
    sm: '20px',
    md: '24px',
    lg: '28px',
    xl: '32px',
    '2xl': '40px',
    '3xl': '48px',
    '5xl': '64px',
    '6xl': '76px',
    '7xl': '84px',
    'bodyXXl-lineHeight': '36px',
  },
};

const width = {
  '8xl': '90rem',
};

const config = {
  darkMode: 'class',
  theme: {
    extend: {
      keyframes: {
        animation: {
          'spin-slow': 'indeterminate 1s infinite linear',
        },
        indeterminate: {
          '40%': { transform: 'translateX(0) scaleX(0.4)' },
          '100%': { transform: 'translateX(100%) scaleX(0.5)' },
        },
        enterFromRight: {
          from: { opacity: '0', transform: 'translateX(200px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        enterFromLeft: {
          from: { opacity: '0', transform: 'translateX(-200px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        exitToRight: {
          from: { opacity: '1', transform: 'translateX(0)' },
          to: { opacity: '0', transform: 'translateX(200px)' },
        },
        exitToLeft: {
          from: { opacity: '1', transform: 'translateX(0)' },
          to: { opacity: '0', transform: 'translateX(-200px)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'rotateX(-10deg) scale(0.9)' },
          to: { opacity: '1', transform: 'rotateX(0deg) scale(1)' },
        },
        scaleOut: {
          from: { opacity: '1', transform: 'rotateX(0deg) scale(1)' },
          to: { opacity: '0', transform: 'rotateX(-10deg) scale(0.95)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        fadeOut: {
          from: { opacity: '1' },
          to: { opacity: '0' },
        },
        slideDown: {
          from: { height: '0px' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        slideUp: {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0px' },
        },
      },
      animation: {
        scaleIn: 'scaleIn 200ms ease',
        scaleOut: 'scaleOut 200ms ease',
        fadeIn: 'fadeIn 200ms ease',
        fadeOut: 'fadeOut 200ms ease',
        enterFromLeft: 'enterFromLeft 250ms ease',
        enterFromRight: 'enterFromRight 250ms ease',
        exitToLeft: 'exitToLeft 250ms ease',
        exitToRight: 'exitToRight 250ms ease',
        slideDown: 'slideDown 300ms cubic-bezier(0.87, 0, 0.13, 1)',
        slideUp: 'slideUp 300ms cubic-bezier(0.87, 0, 0.13, 1)',
      },
      boxShadow: {
        button: '0px 1px 4px rgba(0, 0, 0, 0.05)',
        card: [
          '0px 2px 1px rgba(0, 0, 0, 0.05)',
          '0px 0px 1px rgba(0, 0, 0, 0.25)',
        ],
        popover: [
          '0px 0px 2px rgba(0, 0, 0, 0.2)',
          '0px 2px 10px rgba(0, 0, 0, 0.1)',
        ],
        popup: [
          '0px 0px 1px rgba(0, 0, 0, 0.2)',
          '0px 26px 80px rgba(0, 0, 0, 0.2)',
        ],
        'shadow-2': [
          '0px 0px 1px  rgba(244, 244, 245, 1)',
          '0px 26px 80px rgba(250, 250, 250, 0)',
        ],
        deep: [
          '0px 0px 0px 1px rgba(6, 44, 82, 0.1)',
          '0px 2px 16px rgba(33, 43, 54, 0.08);',
        ],
        modal: [
          '0px 0px 1px rgba(0, 0, 0, 0.2)',
          '0px 26px 80px rgba(0, 0, 0, 0.2)',
        ],
        base: [
          '0px 1px 3px rgba(63, 63, 68, 0.15)',
          '0px 0px 0px 1px rgba(63, 63, 68, 0.05)',
        ],
        focus: '0px 0px 0px 2px #60A5FA;',
      },
      maxWidth: { ...width },
      minWidth: { ...width },
    },
    fontFamily: {
      sans: [
        '"Inter var", sans-serif',
        {
          fontFeatureSettings: '"cv02", "cv03", "cv04", "cv11"',
        },
      ],
      mono: ['Roboto Mono', 'monospace'],
      familjen: ['Familjen Grotesk', 'sans-serif'],
      sriracha: ['Sriracha', 'cursive'],
    },
    screens: {
      sm: '490px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1440px',
      '2xl-md': '1536px',
      '3xl': '1920px',
    },
    fontSize: { ...primitives.fontSize },
    lineHeight: { ...primitives.lineHeight },
    spacing: {
      0: '0px',
      xs: primitives.spacing['025'],
      sm: primitives.spacing['05'],
      md: primitives.spacing['1'],
      lg: primitives.spacing['2'],
      xl: primitives.spacing['3'],
      '2xl': primitives.spacing['4'],
      '3xl': primitives.spacing['5'],
      '4xl': primitives.spacing['6'],
      '5xl': primitives.spacing['8'],
      '6xl': primitives.spacing['10'],
      '7xl': primitives.spacing['12'],
      '8xl': primitives.spacing['16'],
      '9xl': primitives.spacing['20'],
      '10xl': primitives.spacing['24'],
      '11xl': primitives.spacing['32'],
      '12xl': primitives.spacing['40'],
      '13xl': primitives.spacing['48'],
      '14xl': primitives.spacing['60'],
      '15xl': primitives.spacing['64'],
      'form-text-field-height': primitives.spacing['form-text-field-height'],
    },
    colors: {
      surface: {
        basic: {
          default: primitives.colors.grey['50'],
          subdued: primitives.colors.zinc['50'],
          hovered: primitives.colors.grey['100'],
          pressed: primitives.colors.zinc['200'],
          input: primitives.colors.grey['50'],
          active: primitives.colors.zinc['100'],
        },
        primary: {
          default: primitives.colors.blue['500'],
          subdued: primitives.colors.blue['50'],
          hovered: primitives.colors.blue['600'],
          pressed: primitives.colors.blue['700'],
          selected: primitives.colors.blue['100'],
        },
        secondary: {
          default: primitives.colors.amber['300'],
          subdued: primitives.colors.amber['100'],
          hovered: primitives.colors.amber['500'],
          pressed: primitives.colors.amber['600'],
        },
        tertiary: {
          default: primitives.colors.zinc['800'],
          hovered: primitives.colors.grey['700'],
          pressed: primitives.colors.zinc['900'],
          active: primitives.colors.zinc['700'],
        },
        critical: {
          default: primitives.colors.red['500'],
          subdued: primitives.colors.red['50'],
          hovered: primitives.colors.red['600'],
          pressed: primitives.colors.red['700'],
        },
        warning: {
          default: primitives.colors.amber['500'],
          subdued: primitives.colors.amber['50'],
          hovered: primitives.colors.amber['600'],
          pressed: primitives.colors.amber['700'],
        },
        success: {
          default: primitives.colors.green['500'],
          subdued: primitives.colors.green['50'],
          hovered: primitives.colors.green['600'],
          pressed: primitives.colors.green['700'],
        },
        purple: {
          default: primitives.colors.purple['400'],
          hovered: primitives.colors.purple['300'],
          pressed: primitives.colors.purple['500'],
        },
        darktheme: {
          basic: {
            default: primitives.colors.zinc['900'],
            subdued: primitives.colors.zinc['1000'],
            hovered: primitives.colors.zinc['700'],
            pressed: primitives.colors.zinc['800'],
            input: primitives.colors.grey['1100'],
            active: primitives.colors.zinc['800'],
          },
          primary: {
            default: primitives.colors.blue['700'],
            subdued: primitives.colors.blue['1100'],
            hovered: primitives.colors.blue['600'],
            pressed: primitives.colors.blue['800'],
            selected: primitives.colors.blue['1100'],
          },
          secondary: {
            default: primitives.colors.amber['700'],
            subdued: primitives.colors.amber['1100'],
            hovered: primitives.colors.amber['600'],
            pressed: primitives.colors.amber['900'],
          },
          tertiary: {
            default: primitives.colors.grey['50'],
            hovered: primitives.colors.grey['100'],
            pressed: primitives.colors.zinc['200'],
            active: primitives.colors.zinc['100'],
          },
          critical: {
            default: primitives.colors.red['700'],
            subdued: primitives.colors.red['1100'],
            hovered: primitives.colors.red['600'],
            pressed: primitives.colors.red['900'],
          },
          warning: {
            default: primitives.colors.amber['700'],
            subdued: primitives.colors.amber['1100'],
            hovered: primitives.colors.amber['600'],
            pressed: primitives.colors.amber['900'],
          },
          success: {
            default: primitives.colors.green['700'],
            subdued: primitives.colors.green['1100'],
            hovered: primitives.colors.green['600'],
            pressed: primitives.colors.green['900'],
          },
        },
      },
      text: {
        default: primitives.colors.grey['900'],
        soft: primitives.colors.zinc['500'],
        strong: primitives.colors.grey['600'],
        disabled: primitives.colors.grey['400'],
        primary: primitives.colors.blue['600'],
        'on-primary': primitives.colors.grey['50'],
        secondary: primitives.colors.amber['600'],
        critical: primitives.colors.red['600'],
        warning: primitives.colors.amber['600'],
        success: primitives.colors.green['600'],
        darktheme: {
          default: primitives.colors.zinc['100'],
          soft: primitives.colors.zinc['400'],
          strong: primitives.colors.grey['300'],
          disabled: primitives.colors.zinc['600'],
          primary: primitives.colors.blue['400'],
          'on-primary': primitives.colors.zinc['100'],
          secondary: primitives.colors.amber['500'],
          critical: primitives.colors.red['500'],
          warning: primitives.colors.amber['500'],
          success: primitives.colors.green['500'],
        },
      },
      icon: {
        default: primitives.colors.grey['900'],
        soft: primitives.colors.zinc['500'],
        strong: primitives.colors.grey['600'],
        disabled: primitives.colors.grey['400'],
        primary: primitives.colors.blue['600'],
        'on-primary': primitives.colors.grey['50'],
        secondary: primitives.colors.teal['600'],
        critical: primitives.colors.red['600'],
        warning: primitives.colors.amber['600'],
        success: primitives.colors.green['600'],
        darktheme: {
          default: primitives.colors.zinc['100'],
          soft: primitives.colors.zinc['400'],
          strong: primitives.colors.zinc['300'],
          disabled: primitives.colors.zinc['600'],
          primary: primitives.colors.blue['400'],
          'on-primary': primitives.colors.zinc['100'],
          secondary: primitives.colors.amber['500'],
          critical: primitives.colors.red['500'],
          warning: primitives.colors.amber['500'],
          success: primitives.colors.green['500'],
        },
      },
      border: {
        default: primitives.colors.zinc['200'],
        dark: primitives.colors.zinc['300'],
        disabled: primitives.colors.zinc['100'],
        primary: primitives.colors.blue['600'],
        focus: primitives.colors.blue['400'],
        secondary: primitives.colors.amber['600'],
        tertiary: primitives.colors.zinc['600'],
        critical: primitives.colors.red['600'],
        warning: primitives.colors.amber['600'],
        success: primitives.colors.green['600'],
        purple: primitives.colors.purple['500'],
        darktheme: {
          default: primitives.colors.zinc['800'],
          dark: primitives.colors.zinc['700'],
          disabled: primitives.colors.zinc['900'],
          primary: primitives.colors.blue['800'],
          focus: primitives.colors.blue['500'],
          secondary: primitives.colors.amber['800'],
          tertiary: primitives.colors.zinc['200'],
          critical: primitives.colors.red['800'],
          warning: primitives.colors.amber['800'],
          success: primitives.colors.green['800'],
        },
      },
      transparent: 'transparent',
      white: 'white',
      black: 'black',
      dark: {},
    },
  },
  plugins: [
    typography(),
    scrollbar(),
    noScrollbar(),
    noSpinner(),
    perspective(),
  ],
};

export const LightTitlebarColor = config.theme.colors.surface.basic.subdued;
export const ChipGroupPaddingTop = config.theme.spacing.xl;

export default config;
